(function() {var implementors = {};
implementors["pancurses"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a>&lt;<a class=\"enum\" href=\"pancurses/enum.Attribute.html\" title=\"enum pancurses::Attribute\">Attribute</a>&gt; for <a class=\"struct\" href=\"pancurses/struct.Attributes.html\" title=\"struct pancurses::Attributes\">Attributes</a>",synthetic:false,types:["pancurses::attributes::Attributes"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a> for <a class=\"struct\" href=\"pancurses/struct.Attributes.html\" title=\"struct pancurses::Attributes\">Attributes</a>",synthetic:false,types:["pancurses::attributes::Attributes"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a> for <a class=\"enum\" href=\"pancurses/enum.Attribute.html\" title=\"enum pancurses::Attribute\">Attribute</a>",synthetic:false,types:["pancurses::attributes::Attribute"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a>&lt;<a class=\"struct\" href=\"pancurses/colorpair/struct.ColorPair.html\" title=\"struct pancurses::colorpair::ColorPair\">ColorPair</a>&gt; for <a class=\"struct\" href=\"pancurses/struct.Attributes.html\" title=\"struct pancurses::Attributes\">Attributes</a>",synthetic:false,types:["pancurses::attributes::Attributes"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a>&lt;<a class=\"enum\" href=\"pancurses/enum.Attribute.html\" title=\"enum pancurses::Attribute\">Attribute</a>&gt; for <a class=\"struct\" href=\"pancurses/colorpair/struct.ColorPair.html\" title=\"struct pancurses::colorpair::ColorPair\">ColorPair</a>",synthetic:false,types:["pancurses::colorpair::ColorPair"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/bit/trait.BitOr.html\" title=\"trait core::ops::bit::BitOr\">BitOr</a>&lt;<a class=\"struct\" href=\"pancurses/colorpair/struct.ColorPair.html\" title=\"struct pancurses::colorpair::ColorPair\">ColorPair</a>&gt; for <a class=\"enum\" href=\"pancurses/enum.Attribute.html\" title=\"enum pancurses::Attribute\">Attribute</a>",synthetic:false,types:["pancurses::attributes::Attribute"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
